### ISSUE TITLE
Crash on iOS 13.7 and below

### ISSUE THREAD

**Issue by stestaub** [MaikuB/flutter_appauth#198]
The plugin seems only to work on iOS 14.4 If I run the example application on iOS 13.7 or below, the app crashes as soon as the method `_appAuth.token()` is called.

Sadly, the crash happens silently, even in verbose mode. It just kills the app (see attached verbose logs).

Tested iOS versions:
- iOS 11.4: Crash
- iOS 13.7: Crash
- iOS 14.4 Works as expected

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-arm, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] VS Code (version 1.54.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

Pubspec:
```yaml
name: appauth_crash
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^1.0.0
  http: ^0.13.0
```

Verbose log:
[flutter.log](https://github.com/MaikuB/flutter_appauth/files/6189820/flutter.log)
